FROM ruby:3.3.5 AS nodejs

WORKDIR /tmp

RUN curl -LO https://nodejs.org/dist/v20.17.0/node-v20.17.0-linux-x64.tar.xz
RUN tar xvf node-v20.17.0-linux-x64.tar.xz
RUN mv node-v20.17.0-linux-x64 node

FROM ruby:3.3.5

COPY --from=nodejs /tmp/node /opt/node
ENV PATH /opt/node/bin:$PATH

RUN curl -o- -L https://yarnpkg.com/install.sh | bash
ENV PATH /root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:$PATH

RUN gem install bundler

WORKDIR /app

RUN bundle config set path vendor/bundle

CMD ["bash"]